README.md

Replace "mcumgr" with "mynewt-mcumgr".
Signed-off-by: Ding Tao <miyatsu@qq.com>

Readme.md: Fix bad links in file README.md

---

cmd/img_mgmt/src/img_mgmt_state.c

_cbor_value_copy_string() (invoked by cbor_read_object()) adds a
null-character to the byte string.
Not adding this additional byte to the buffer obviously corrupts the memory.
Signed-off-by: Olivier Martin <olivier.martin@proglove.de>
cc: @carlescufi, @nvlsianpu

cmd: img_mgmt: Add an extra byte to the 'hash' buffer

---

README.md

Link the names of the OS-specific documentation for Mynewt and Zephyr in
the Readme files.
Signed-off-by: Johannes Hutter <johannes@proglove.de>

Readme.md: Link OS-specific documentation

---

cmd/img_mgmt/syscfg.yml
cmd/os_mgmt/Kconfig
cmd/os_mgmt/src/os_mgmt.c
cmd/os_mgmt/src/os_mgmt_config.h

Application might not be interested in using those commands and
disabling them allows to save 628 bytes of flash.
Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

Allow to configure taskstat and echo commands support

---

Kconfig
cmd/fs_mgmt/Kconfig
cmd/img_mgmt/Kconfig
cmd/log_mgmt/Kconfig
cmd/stat_mgmt/Kconfig

This synchronizes Kconfig with current Zephyr master.
Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

Use a short, consistent style for prompts in Kconfig

---

cmd/img_mgmt/src/img_mgmt.c

This fix missing upload start event on upload resume and missing
ongoing event in case upload is restarted due to invalid offset.
Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>

Fix missing upload events callbacks

---

protocol.md

This PR is based on some documentation from [Adafruit_Mynewt](https://github.com/adafruit/Adafruit_Mynewt/tree/master/docs), and attempts to describe some of the basics of the nmp protocol used by both newtmgr and mcumgr.
The original documentation is based on an early release of the protocol in the context of Apache Mynewt, but an attempt has been made to bring the links and basic details up to date with the golang based `newtmgr` and the C based `mcumgr` projects.
Further extensions to this document are of course welcome and necessary to help people implement nmp in their mobile, desktop or other applications.

Added initial protocol description for NMP/SMP

---

protocol.md

This PR makes some minor changes to `protocol.md` to point to the correct URI for mcumgr-cli, and some general cleanup to change references to SMP and `mcumgr` instead of NMP and `newtmgr`.

Fixed URI for `mcumgr-cli`, minor cleanup

---

transport/smp-console.md

The 128 maximum size applies to the entire frame including header, CRC, and terminating newline.

smp-console.md: clarify 128-byte max frame size

---

cborattr/src/cborattr.c

Add missing break statement to Boolean type.
Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

cborattr: Fix conversion between cbortype and cborattr

---

cmd/log_mgmt/include/log_mgmt/log_mgmt.h
cmd/log_mgmt/port/mynewt/src/mynewt_log_mgmt.c
cmd/log_mgmt/port/zephyr/src/zephyr_log_mgmt.c
cmd/log_mgmt/src/log_mgmt.c

- log_mgmt errors are separated out now to support backwards compatible
behavior with newtmgr in mynewt-core

log_mgmt: Seperate out log_mgmt errors

---

version.yml

Newt requires this file to determine which version a given commit in a repo corresponds to.
Without this file, `newt upgrade` reports the warnings similar to these:
```
WARNING: Could not detect version of installed repo "apache-mynewt-mcumgr"; assuming 0.0.0/17a64fb7609c2fc71d7acf55889bad99d27c0c36
WARNING: apache-mynewt-mcumgr:17a64fb7609c2fc71d7acf55889bad99d27c0c36 does not contain a `version.yml` file.
WARNING: Could not detect version of requested repo apache-mynewt-mcumgr:17a64fb7609c2fc71d7acf55889bad99d27c0c36; assuming 0.0.0
```
In master, the version should always be 0.0.0.

Add `version.yml` file.

---

cmd/log_mgmt/src/log_mgmt.c

The change to the format of this response causes parsing issues for some clients.  To resolve these issues, restore the old format as follows:
1. Re-add the top-level `next_index` field.  It will always have a value of 0 (a single "next index" no longer exists).  This field will be considered deprecated with plans to remove it in the future.
2. Remove the per-log `next_index` field.

log_mgmt: Restore old `log show` response format

---

cmd/log_mgmt/include/log_mgmt/log_mgmt_impl.h
cmd/log_mgmt/port/mynewt/src/mynewt_log_mgmt.c
cmd/log_mgmt/src/log_mgmt.c
cmd/log_mgmt/src/stubs.c

- Earlier watermark was set for the first entry, it should be the last
one, this watermark can get persisted hence, we need to only remember or
persist the watermark once at the end of the response.
This fixes https://github.com/apache/mynewt-mcumgr/issues/44

log_mgmt:watermark should be set at last log entry

---

cborattr/src/cborattr.c

Sets len to 0 by default so it would never be used uninitialized.

cborattr.c: Fix uninitialized variable.

---

cmd/log_mgmt/port/mynewt/src/mynewt_log_mgmt.c

Currently mcumgr log level_list command isn't working because it expects LOG_LEVEL_IDX to return NULL instead of the string "UNKNOWN" when a non valid level index is provided.

Handle "UNKNOWN" on log_mgmt_impl_get_level

---

cmd/img_mgmt/src/img_mgmt_state.c

- This was missed out during the transition from newtmgr to
mcumgr

img_mgmt: Add img_mgmt_dfu_confirmed() callback in img_mgmt_state.c

---

cmd/log_mgmt/src/log_mgmt.c

- After filling up log responses, set the watermark as well. We have to
honor LOG_MGMT_ERR_UNKNOWN.

log_mgmt: Set watermark on filling up log rsp

---

cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c

There is API to get stack usage, no need to access os_task directly.

cmd/os_mgmt: Use Mynewt API to get stack usage

---

cmd/img_mgmt/include/img_mgmt/image.h
cmd/img_mgmt/src/img_mgmt.c

- Protected TLVs should get parsed first and then the regular TLVs
should get parsed

img_mgmt: TLVs were not getting parsed correctly

---

cborattr/src/cborattr.c

This is a temporary solution so Zephyr may compile while zephyr doesn't feature the MGMT_CBORATTR_MAX_SIZE Kconfig val.

Set CBORATTR_MAX_SIZE default when no Kconfig counterpart is defined.

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

Zephyr will soon no longer add the drivers subdirectory of the include
hierarchy to the search path, so references to driver headers must
include the drivers/ prefix.
Signed-off-by: Peter A. Bigot <peter.bigot@nordicsemi.no>

cmd: img_mgmt: fix driver include path

---

samples/smp_svr/mynewt/syscfg.yml

Based on the investigation we did, it seems the stack was overflowing by 92 bytes, so I am going to increase it by 96 bytes from the previous value which was 468.

smp_svr: Change the stack size to 564

---

samples/smp_svr/mynewt/syscfg.yml

- On the mynewt side, OS main stack size should be set to 568 since taskstat
shows the 8 byte aligned value for the stack size

mynewt_smp_svr: Stack is 8 byte aligned, 564 -> 568

---

cmd/img_mgmt/src/img_mgmt_util.c

In `img_mgmt_ver_str()`the iv_revision field was getting converted twice instead of iv_build_num, resulting in the incorrect version string output.

Fix build_num in image_version string conversion

---

cmd/os_mgmt/port/zephyr/src/zephyr_os_mgmt.c

The CONFIG_ prefix was missing.
Found with a work-in-progress scripts/kconfig/lint.py check.
This symbol is defined in kernel/Kconfig in Zephyr.
Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>

kconfig: Fix broken ref. to THREAD_STACK_INFO from Zephyr

---

cborattr/src/cborattr.c
mgmt/src/mgmt.c

Changes needed due to overwrite of Zephyr fork of Tinycbor with
mynewt-core version.

ext: lib: mgmt: Enabling Zephyr/mynewt-core version of tinycbor

---

samples/smp_svr/zephyr/sample.yaml

Name of the board is changing in the zephyr-rtos:
zephyrproject-rtos/zephyr#23447
This patch aligns the board name used which is required for suppression
of build warnings.
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

zephyr: board nrf51_pca10028 renamed to nrf51dk_nrf51422

---

cmd/fs_mgmt/include/fs_mgmt/fs_mgmt_config.h

File download worked only for files small enough to fit into small mcumgr
buffer, dedicated for CBOR encoding. Because file read buffer size is
independent from the size of CBOR encoding buffer and part of CBOR buffer
is used outside of control of download backend, it could happen that the
chunk read could not fit into actual free space left within CBOR buffer,
automatically failing the download.
This is alternative, less code invasive, solution to https://github.com/apache/mynewt-mcumgr/pull/65 which does compile time, instead of run time, compilation.

fs_mgmt: Fix file download for Zephyr

---

CMakeLists.txt

DEPENDS ON:
zephyrproject-rtos/tinycbor#13
It is no longer needed to add TINYCBOR to list of interface libraries.

zephyr: TinyCBOR has been removed from interface libraries

---

samples/omp_svr/mynewt/syscfg.yml

omp_svr had the same problem as described on https://github.com/apache/mynewt-mcumgr/pull/59 for smp_svr. This PR increases the stack size to 568 since the stack was overflowing by 90 bytes in this case.

omp_svr: Change the stack size to 568

---

cmd/os_mgmt/port/zephyr/src/zephyr_os_mgmt.c

The new API does not accept integer types for timeouts, instead it uses
k_timeout_t structure.

zephyr: Convert k_timer calls to new API

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

Update member access of context.
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

zephyr: adapt to changes in flash_img.c

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
samples/smp_svr/zephyr/src/main.c

It was possible that the function tried to eras non erase-block-size
aligned number of bytes witch might have cause failure.
Additionally the image trailer area might have been not erased at all.
Reworked implementation so:
- the erase request is corrected to erase proper amount of memory
- erase of image trailer is ensured.
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>
PR initiated per request from @nvlsianpu (https://github.com/zephyrproject-rtos/mcumgr/pull/22)

cmd/img_mgmt/port/zephyr: fix to img_mgmt_impl_erase_image_data()

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
samples/smp_svr/zephyr/src/main.c

Convert to use C99 types as we intend to deprecate the zephyr
specific integer types.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

zephyr: Convert from Zephyr to C99 types

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

Fix print format specifier which throws warnings when minimal libc is not used. 
The base type of off_t varies depending on whether minimal libc is used. 
Minimal libc defines off_t as int, while gcc-arm-eabi-2020-q2 for example defines it as a long.
The value is explicitly cast to a long and the long format specifier used to fix the warning.
Signed-off-by: Jordan Yates <jordan.yates@data61.csiro.au>

cmd/img_mgmt/port/zephyr: off_t print format fix

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

Following warning message appears when building Zephyr for qemu_x86 platform:
/zephyr/include/logging/log_core.h:238:10: warning: format '%x' \
expects argument of type 'unsigned int', but argument 3 has type \
'long unsigned int' [-Wformat=]
Suppress that by casting to unsigned int.
Following warning messages appear when building Zephyr for
native_posix_64 platform:
/zephyr/include/logging/log_core.h:238:10: warning: format ‘%x’ \
expects argument of type ‘unsigned int’, but argument 2 has type \
‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
Suppress that by using %zx instead of %x.
Signed-off-by: Marcin Niestroj <m.niestroj@grinn-global.com>

cmd/img_mgmt/port/zephyr: suppress warnings with logging enabled

---

cmd/fs_mgmt/port/zephyr/src/zephyr_fs_mgmt.c

With addition of open flags to fs_open calls, all invocations that do
not provide them require change.

zephyr: Add file open flags to fs_open calls

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

Follow update done with: https://github.com/zephyrproject-rtos/zephyr/pull/24873
That makes struct device const.

zephyr: constify struct device

---

cmd/img_mgmt/src/img_mgmt.c

This is a fix for devices in the field using mcuboot versions v1.6.0 or less.
If a firmware update is attempted with a corrupt image and a power outage or
reset occurs while the bootloader* is erasing the corrupt image then the
secondary (slot-1) can be left in a state where the bootloader has not
properly released slot-1 and a DFU transfer can no longer happen. Attempts
to execute the image erase command will fail with 6 (MGMT_ERR_EBADSTATE).
This commit fixes this issue by adding an additional requirement to determine
if a slot is 'in use': the image must also be valid. If this additional
requirement is not also met then the slot is considered not in use.
* The issue was originally discovered with Zephyr v1.14 LTS and mcuboot release
v3.1 and a fix for mcuboot has been applied here: …

Fix image erase command for partial slot-1 erase

---

cmd/shell_mgmt/CMakeLists.txt
cmd/shell_mgmt/include/shell_mgmt/shell_mgmt.h
cmd/shell_mgmt/include/shell_mgmt/shell_mgmt_config.h
cmd/shell_mgmt/include/shell_mgmt/shell_mgmt_impl.h
cmd/shell_mgmt/port/zephyr/src/zephyr_shell_mgmt.c
cmd/shell_mgmt/src/shell_mgmt.c
cmd/shell_mgmt/src/stubs.c

I noticed that the shell command was not supported on zephyr, but I desired this functionality for my application. I have implemented the shell_mgmt command handler so that `shell exec` is supported from the mcumgr cli. It will now return the shell command status code, and if possible it will return the shell output as a string.
I did not implement necessary implementations for mynewt os in the PR so only zephyr is supported.
If testing on zephyr, the application will require a custom KConfig option `CONFIG_MCUMGR_CMD_SHELL_MGMT=y` and the shell backend will need to be set to dummy.
```
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_SHELL_BACKEND_DUMMY=y
```
Because of a limitation in the zephyr shell implementation, the actual shell output can only be captured and returned to mcumgr when using the …

Implement shell management command handlers.

---

cmd/img_mgmt/include/img_mgmt/img_mgmt_impl.h
cmd/img_mgmt/port/mynewt/src/mynewt_img_mgmt.c
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
cmd/img_mgmt/src/img_mgmt.c

Add a new abstraction to the image port implementation to get the value a flash device is erased to, and update the image manager to expect the correct values when reading erased data at the image header, etc.

Add image upload support for flash erased at 0

---

cmd/img_mgmt/include/img_mgmt/image.h
cmd/img_mgmt/include/img_mgmt/img_mgmt.h
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
cmd/img_mgmt/src/img_mgmt.c

The commit adds IMAGE_F_ROM_FIXED_ADDR flag that allows to use
ih_load_addr to identify the flash address the image is intendant to
start at.
The code, that supports this flag, will reject image before attempting
flash write if slot address differs from the base address of the image.
The feature can be used to mark Direct-XIP images with slot address
they are intended for.
The CONFIG_IMG_MGMT_REJECT_DIRECT_XIP_MISMATCHED_SLOT has been added
to turn the featre on.

zephyr: Add support for image ROM address verification

---

cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c

GCC complains about a strncpy call when build using build_profile speed.
This warning indicates a possible string truncation. The only proper
solution I could find was to decrease the buffer size and explicitly
set a zero byte.
Error: repos/apache-mynewt-mcumgr/cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c: In function 'os_mgmt_impl_task_info':
repos/apache-mynewt-mcumgr/cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c:92:5: error: 'strncpy' specified bound 32 equals destination size [-Werror=stringop-truncation]
92 |     strncpy(out_info->oti_name, task->t_name, sizeof out_info->oti_name);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

mynewt: Fix strncpy warning

---

mgmt/src/mgmt.c

Fix usage of prev when curr==group, and add checking for invalid parameter. Fix issues found after #108

Fix unitialized variable warning

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The mcumgr should relay on single decision point for upload flash area selection; instead the `img_mgmt_find_best_area_id` and FLASH_AREA_ID macros were used for similar purpose through the code, even though `img_mgmt_find_best_area_id` is more restrictive and may not agree with `FLASH_AREA_ID`.

Use img_mgmt_find_best_area_id to select upload slot instead of FLASH_AREA_ID

---

cborattr/include/cborattr/cborattr.h
cborattr/src/cborattr.c

This PR adds half-float support to MCUMGR.
We are using MCUMGR to transfer floating-point data
to our device and have found this can be transferred
as half, single or double precision float depending upon
the value being transferred.
Requested by: Greg Leach <greg.leach@lairdconnect.com>

Bug #18312 Add support for half-floats to MCUMGR

---

cborattr/src/cborattr.c

`cbor_encode_half_float` was being called passing in the halffloat (uint16_t) by value, but `cbor_encode_floating_point` accepts a `void *` pointer. This is already done automatically for float and double encoding, but must be done manually for halffloat.
Fixes the current CI issues seen on nimble and core.

Fix encoding usage for halffloat

---

cmd/img_mgmt/src/img_mgmt_state.c

The commit changes function img_mgmt_state_flasg functions to use
IMG_MGMT_BOOT_CURR_SLOT in comparisons as a currently running slot
number instead of previously hard-coded 0.
The change allows to correctly identify active partition when
application is running from different slot than 0.

img_mgmt: Use IMG_MGMT_BOOT_CURR_SLOT as current running slot ID

---

cmd/img_mgmt/src/img_mgmt_state.c

rc assigns were leftover of state before adding `done:` marker. They
were not used as actual return values no more, as first thing that
happens at done marker is overwrite of them

img_mgmt_state_set_pending: corrected error handling

---

samples/smp_svr/zephyr/prj.conf
samples/smp_svr/zephyr/prj_tiny.conf

The usage of theses kconfig have changed in
zephyrproject-rtos/zephyr#26447
Hence their values should be updated.
Signed-off-by: Xavier Chapron <xavier.chapron@stimio.fr>

samples: smp_svr: zephyr: Update MTU Kconfig values

---

cmd/img_mgmt/include/img_mgmt/img_mgmt.h
cmd/img_mgmt/src/img_mgmt.c

The commit extends img_mgmt_upload_req with image member that will
be used to hold image number; it also adds code that picks the
image number from update frame.

img_mgmt: Add interpretation of "image" parameter

---

cmd/img_mgmt/src/img_mgmt.c

- DFU stop callback needs to be called when erase is performed, since the DFU state of the image gets cleared

cmd/img_mgmt: Call dfu stop cb on erase

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The PR is series of fixes that to the Zephyr fork that:
- change slot selection logic of `img_mgmt_find_best_area_id`, renames it to `mgm_mgmt_get_unused_area_id` and adds single parameter; now the function will accept as -1 as a parameter that request any upgreadable slot area_id, selected from first two slots, or positive number that is direct slot request; direct slot request may not be successful for first two slots as they are checked for usage, while no such checks are performed for all other slots.  All other slots are just checked for existence.
- add missing check, of `img_mgmt_get_second_slot_area_id` return, in `img_mgmt_impl_erase_slot`;
- changes the `img_mgmt_impl_write_image_data` to use the `area_id` from the state of mcumgr, so the currently selected for operation, …

Zephyr fixes

---

samples/smp_svr/zephyr/prj.conf
samples/smp_svr/zephyr/prj_tiny.conf

The addition of image interpretation requires increase in stack
size.

samples/smp_svr/zephyr: Update stack size

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The change alters Zephyr port of mcumgr to use "image" parameter,
from update packet, to identify slot the update should be written to.
The number of available images/slots have also been extended with
image_2 and image_3.
WARNING: Due to mcumgr always sending "erase" command, which is
hardcoded to erase slot number 1, to upload to slot > 2, the -e
switch to mcumgr, which means no erase, image upload is required;
otherwise innocent slot 1 will be erased while other slot is uploaded.

zephyr: Allow to select slot for DFU as image

---

cmd/img_mgmt/include/img_mgmt/img_mgmt_impl.h
cmd/img_mgmt/port/mynewt/src/mynewt_img_mgmt.c
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
cmd/img_mgmt/src/img_mgmt_state.c

The PR contains series of commits that add slot parameter to `img_mgmt_impl_swap_type` and change system ports to support it.
It also moves slot number checking asserts to system specific implementation of the `img_mgmt_impl_swap_type`.

Parametrize img_mgmt_impl_swap_type

---

cmd/img_mgmt/src/img_mgmt.c

Start, ongoing and complete states are now used in the callback
Signed-off-by: Jamie McCrae <jamie.mccrae@lairdconnect.com>
Fixes https://github.com/apache/mynewt-mcumgr/issues/136
Output from callback in a zephyr application after these changes:
```
[00:02:04.021,718] <err> Got callback: 2, 1, 1, 0
[00:02:28.120,300] <err> Got callback: 2, 1, 1, 1
[00:02:28.260,223] <err> Got callback: 2, 1, 1, 1
[00:02:28.300,292] <err> Got callback: 2, 1, 1, 1
[00:02:28.330,291] <err> Got callback: 2, 1, 1, 1
[00:02:28.370,666] <err> Got callback: 2, 1, 1, 1
[00:02:28.405,303] <err> Got callback: 2, 1, 1, 1
[00:02:28.444,946] <err> Got callback: 2, 1, 1, 1
[00:02:28.480,316] <err> Got callback: 2, 1, 1, 1
[00:02:28.510,314] <err> Got callback: 2, 1, 1, 1
[00:02:28.549,560] <err> Got callback: 2, 1, 1, …
```

img_mgmt: fix callback parameter values

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The img_mgmt_get_unused_slot_area_id has been incorrectly
reacting to -1 parameter, which is valid parameter for single
image configuration.

zephyr: Fix erase command failing for multi-image configuration

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The img_mgmt_get_unused_slot_area_id is used as verification function,
for user provided image number, and as such should return -1 when
incorrect image number is given without logging assertion.
The commit fixes above problem, and additionally it changes the error
codes returned when a slot/image can not be correctly mapped,
to a specific flash area id, to MGM_ERR_ENOENT.

zephyr: Fix assert when image number out of range

---

cmd/img_mgmt/include/img_mgmt/img_mgmt_config.h
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The IMG_MGMT_UPDATABLE_IMAGE_NUMBER should be used in
then CONFIG_IMG_MGMT_UPDATABLE_IMAGE_NUMBER; this allows defaulting
IMG_MGMT_UPDATABLE_IMAGE_NUMBER when the config option is not defined
and avoid compilation errors.

zephyr: Do not use CONFIG_IMG_MGMT_UPDATABLE_IMAGE_NUMBER directly

---

cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c

The zephyr_img_mgmt_flash_area_id is allowed to return negative
value as error, but due to lack of checks that value could be
passed to functions with poor parameter checks, causing a softare
to crash.

zephyr: Fix usage of zephyr_img_mgmt_flash_area_id

---

cborattr/src/cborattr.c

In the while loop in the function cbor_internal_read_object
there is no error handling when the cbor_value_advance
reports an error. This may end up in a never ending loop.
This seems to be fixing the issue reported in https://github.com/apache/mynewt-mcumgr/issues/140
Signed-off-by: Even Falch-Larsen <even.falch.larsen@nomono.co>

cborattr: fixes missing error handling

---

cmd/os_mgmt/port/mynewt/pkg.yml

Code already  uses sys/reboot only if LOG_SOFT_RESET is enabled.
Now package is also included only if LOG_SOFT_RESET is present,
this removes unnecessary package inclusion that result in
requirement to have reboot log image area that package will
not use when flag is not present.

os_mgmt/mynewt: Make package dependency conditional

---

cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c

package @apache-mynewt-mcumgr/cmd/img_mgmt is only
used when LOG_SOFT_RESET is defined.
This change moves #include to line to remove build error
when LOG_SOFT_RESET is 0.

os_mgmt/mynewt: Fix build when LOG_SOFT_RESET is off

---

cmd/os_mgmt/port/mynewt/syscfg.yml

LOG_SOFT_REBOOT was defined in sys/reboot package.
This package however never used this for anything.
Moreover, some packages in mynewt-core used this
value to conditionally include sys/reboot.
Now LOG_SOFT_REBOOT is moved to package that actually
uses it for inclusion of sys/reboot.
related PR in mynewt-core: https://github.com/apache/mynewt-core/pull/2710

os_mgmt/mynewt: Fix log reboot confusion

---

cborattr/src/cborattr.c
cmd/fs_mgmt/port/zephyr/src/zephyr_fs_mgmt.c
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt.c
cmd/img_mgmt/port/zephyr/src/zephyr_img_mgmt_log.c
cmd/os_mgmt/port/zephyr/src/zephyr_os_mgmt.c
cmd/shell_mgmt/port/zephyr/src/zephyr_shell_mgmt.c
cmd/stat_mgmt/port/zephyr/src/zephyr_stat_mgmt.c
samples/smp_svr/zephyr/src/main.c

Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.

zephyr: update include paths to use <zephyr/...>

---

README.md

Installation procedure changed post the go 1.18 release. This change brings the installation instructions in line with what is given in the [Zephyr MCUmgr instructions](https://github.com/zephyrproject-rtos/zephyr/blob/v3.2.0/doc/services/device_mgmt/mcumgr.rst).

Update install instructions for go >=1.18

---

cmd/img_mgmt/port/mynewt/pkg.yml
cmd/img_mgmt/port/mynewt/syscfg.yml
cmd/log_mgmt/port/mynewt/syscfg.yml
cmd/os_mgmt/pkg.yml
cmd/os_mgmt/syscfg.yml
cmd/stat_mgmt/port/mynewt/pkg.yml
cmd/stat_mgmt/port/mynewt/syscfg.yml

This allows the app or target to rearrange package initialziation order via syscfg overrides

Use syscfg settings for sysinit stage numbers

---

cborattr/test/src/testcases/cborattr_decode_int_array.c
cborattr/test/src/testcases/cborattr_decode_object.c
cborattr/test/src/testcases/cborattr_decode_simple.c
cborattr/test/src/testcases/cborattr_decode_unnamed_array.c

This allows running newt unit tests on 64-bit architecture. Without it, compilation errors were occurring (type mismatch).

cborattr/test: Add type casting for 64-bit architecture

---

cmd/img_mgmt/port/mynewt/src/mynewt_img_mgmt.c

Normally two flash areas are available FLASH_AREA_IMAGE_0 and FLASH_AREA_IMAGE_1.
For cases bootloader is able to write to FLASH_AREA_IMAGE_0 directly (USB DFU) bsp used to define fake FLASH_AREA_IMAGE_1 with empty size. Bootloader with DFU functionality other then mcumgr still uses img_mgmt functions to confirm image. This change changes functions that operate on FLASH_AREA_IMAGE_1 to return MGMT_ERR_ENOTSUP when FLASH_AREA_IMAGE_1 is not defined. This allows to have bsp.yml without artificial zero sized areas.

Allow build when no FLASH_AREA_IMAGE_1 is defined

---

cmd/fs_mgmt/port/mynewt/pkg.yml
cmd/fs_mgmt/port/mynewt/src/mynewt_fs_mgmt.c

There were incompatible types used
and typo in variable names preventing this
to ever build.
Dependency to cmd/fs_mgmt was also incorrect in
cmd/mynewt_fs_mgmt
Mynwet package now have"
```yml
whole_archive : true
```
to chose actual read and write implementations instead of stub functions.
It look like this functionality was never tried

Mynwet fixes for accessing file system

---

cmd/log_mgmt/port/mynewt/src/mynewt_log_mgmt.c

- trailer_length and size of the trailer should be subtracted from the log entry being read to get only the log entry data

cmd/log_mgmt: Subtract trailer length on log read

---

cmd/os_mgmt/port/mynewt/src/mynewt_os_mgmt.c

Build failed with GCC 9-2020-q2 and GCC 10.3-2021.10 because of the VLA warning in `os_mgmt_impl_datetime_info`. This PR fixes this issue implemented in #181 by removing the variable length array.

cmd/os_mgmt: remove VLA usage in datetime command
